# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
        with:
          ref: ${{ github.head_ref }}

      # install pandoc
      - name: install pandoc
        run: sudo apt install pandoc -y
          
      # convert file
      - name: build epub
        run: ./convert.sh
              
      # commit epub  
      - uses: stefanzweifel/git-auto-commit-action@v4      
        with:
          commit_message: updated html and epub
